before_install:
  - gem install bundler
language: ruby
cache: bundler
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
addons:
  code_climate:
    repo_token: 7488b157e7b7f48eac865a9f830fe90a39e6ac10b17f854e17b9529e1854762c
after_success:
  - bundle exec codeclimate-test-reporter
