before_install:
  - gem install bundler
language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.2
  - ruby-head
  - jruby-head
  - rbx
env:
- COVERALLS=true
matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx
